In [2]:
import pandas as pd 
df=pd.read_csv("http://13.234.66.67/summer19/datasets/info.csv")

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [13]:
x=df.iloc[:,0:].values
x

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [14]:
# removing missing values and replacing missing value with some relevant data 
#df.describe()
from sklearn.preprocessing import Imputer

In [15]:
imp=Imputer(missing_values='NaN',axis=0,strategy='mean')

In [17]:
impute=imp.fit(x[:,1:3]) # this is just fitting of column that we want to process

In [20]:
#now time for transforming fitted column 
x[:,1:3]=impute.transform(x[:,1:3])

In [21]:
x

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 63777.77777777778, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.77777777777778, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [24]:
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [25]:
#string labeling into intor float
from sklearn.preprocessing import LabelEncoder

In [26]:
cont=LabelEncoder() # this is for country label 

In [27]:
# now apply column 
x[:,0]=cont.fit_transform(x[:,0])

In [28]:
x

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [29]:
# labelling last column 
p=LabelEncoder()

In [30]:
x[:,3]=p.fit_transform(x[:,3])

In [31]:
x


array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [32]:
# now encoding first column  --- making sub column of first column 
from sklearn.preprocessing import OneHotEncoder 

In [33]:
firstcl=OneHotEncoder(categorical_features=[0]) #identifying exact column number where we want to make category

In [36]:
x=firstcl.fit_transform(x).toarray() #after transformation we need to convert into numpy array

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [39]:
x.astype(int)  # to show in int only

array([[    1,     0,     0,    44, 72000,     0],
       [    0,     0,     1,    27, 48000,     1],
       [    0,     1,     0,    30, 54000,     0],
       [    0,     0,     1,    38, 61000,     0],
       [    0,     1,     0,    40, 63777,     1],
       [    1,     0,     0,    35, 58000,     1],
       [    0,     0,     1,    38, 52000,     0],
       [    1,     0,     0,    48, 79000,     1],
       [    0,     1,     0,    50, 83000,     0],
       [    1,     0,     0,    37, 67000,     1]])