In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv("titanic.csv")

In [3]:
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
5           0       3                                    Mr. James Moran   
6           0       1                             Mr. Timothy J McCarthy   
7           0       3                      Master. Gosta Leonard Palsson   
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson   
9           1       2                 Mrs. Nicholas (Adele Achem) Nasser   
10          1       3                     Miss. Marguerite Rut Sandstrom   
11          1       1                            Miss. Elizabeth Bonnell   
12          0       3                      Mr. William Henry Saundercock   
13          0       3                         Mr. Anders Johan Andersson   
14          0       3                Miss. Hulda Amanda Adolfina Vestrom   
15          1       2                     Mrs. (Mary D Kingcome) Hewlett   
16          0       3                                Master. Eugene Rice   
17          1       2                        Mr. Charles Eugene Williams   
18          0       3  Mrs. Julius (Emelia Maria Vandemoortele) Vande...   
19          1       3                             Mrs. Fatima Masselmani   
20          0       2                                Mr. Joseph J Fynney   
21          1       2                               Mr. Lawrence Beesley   
22          1       3                                 Miss. Anna McGowan   
23          1       1                        Mr. William Thompson Sloper   
24          0       3                       Miss. Torborg Danira Palsson   
25          1       3  Mrs. Carl Oscar (Selma Augusta Emilia Johansso...   
26          0       3                             Mr. Farred Chehab Emir   
27          0       1                      Mr. Charles Alexander Fortune   
28          1       3                                Miss. Ellen O'Dwyer   
29          0       3                                 Mr. Lalio Todoroff   
..        ...     ...                                                ...   
857         0       2                         Mr. Frederick Edward Giles   
858         1       1  Mrs. Frederick Joel (Margaret Welles Barron) S...   
859         0       3                           Miss. Dorothy Edith Sage   
860         0       2                              Mr. John William Gill   
861         1       2                            Mrs. (Karolina) Bystrom   
862         1       2                        Miss. Asuncion Duran y More   
863         0       1                Mr. Washington Augustus II Roebling   
864         0       3                         Mr. Philemon van Melkebeke   
865         1       3                     Master. Harold Theodor Johnson   
866         0       3                                   Mr. Cerin Balkic   
867         1       1    Mrs. Richard Leonard (Sallie Monypeny) Beckwith   
868         0       1                            Mr. Frans Olof Carlsson   
869         0       3                         Mr. Victor Vander Cruyssen   
870         1       2               Mrs. Samuel (Hannah Wizosky) Abelson   
871         1       3                           Miss. Adele Kiamie Najib   
872         0       3                       Mr. Alfred Ossian Gustafsson   
873         0       3                                Mr. Nedelio Petroff   
874         0       3                                  Mr. Kristo Laleff   
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter   
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley   
877         0       3                                

In [4]:
x=df.iloc[:,0:].values


In [5]:
x

array([[0, 3, 'Mr. Owen Harris Braund', ..., 1, 0, 7.25],
       [1, 1, 'Mrs. John Bradley (Florence Briggs Thayer) Cumings', ...,
        1, 0, 71.2833],
       [1, 3, 'Miss. Laina Heikkinen', ..., 0, 0, 7.925],
       ...,
       [0, 3, 'Miss. Catherine Helen Johnston', ..., 1, 2, 23.45],
       [1, 1, 'Mr. Karl Howell Behr', ..., 0, 0, 30.0],
       [0, 3, 'Mr. Patrick Dooley', ..., 0, 0, 7.75]], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
# converting sex column into int 
x[:,3]=le.fit_transform(x[:,3])

In [9]:
x # 1 is for male and 0 is for female

array([[0, 3, 'Mr. Owen Harris Braund', ..., 1, 0, 7.25],
       [1, 1, 'Mrs. John Bradley (Florence Briggs Thayer) Cumings', ...,
        1, 0, 71.2833],
       [1, 3, 'Miss. Laina Heikkinen', ..., 0, 0, 7.925],
       ...,
       [0, 3, 'Miss. Catherine Helen Johnston', ..., 1, 2, 23.45],
       [1, 1, 'Mr. Karl Howell Behr', ..., 0, 0, 30.0],
       [0, 3, 'Mr. Patrick Dooley', ..., 0, 0, 7.75]], dtype=object)

In [10]:
x[:,2]=le.fit_transform(x[:,2])

In [11]:
x

array([[0, 3, 601, ..., 1, 0, 7.25],
       [1, 1, 822, ..., 1, 0, 71.2833],
       [1, 3, 171, ..., 0, 0, 7.925],
       ...,
       [0, 3, 99, ..., 1, 2, 23.45],
       [1, 1, 524, ..., 0, 0, 30.0],
       [0, 3, 605, ..., 0, 0, 7.75]], dtype=object)

In [12]:
# now using OneHotEncoder on survived column 
from sklearn.preprocessing import OneHotEncoder

In [13]:
firstcl=OneHotEncoder(categorical_features=[0])

In [14]:
x=firstcl.fit_transform(x).toarray() 

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
x.astype(int)

array([[ 1,  0,  3, ...,  1,  0,  7],
       [ 0,  1,  1, ...,  1,  0, 71],
       [ 0,  1,  3, ...,  0,  0,  7],
       ...,
       [ 1,  0,  3, ...,  1,  2, 23],
       [ 0,  1,  1, ...,  0,  0, 30],
       [ 1,  0,  3, ...,  0,  0,  7]])

In [16]:
features=x

In [17]:
label=x[:,0]

In [18]:
label1=np.where(label==1,'dead',label)

In [19]:
label1=np.where(label1==0,'survived',label)

/home/ubuntu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


In [20]:
label=np.where(label==1,'dead',label)
label


array(['dead', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0',
       '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead', '0.0',
       'dead', '0.0', 'dead', '0.0', '0.0', '0.0', 'dead', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead',
       'dead', '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', '0.0',
       'dead', 'dead', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0',
       '0.0', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead', 'dead', '0.0',
       'dead', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead', 'dead',
       '0.0', '0.0', 'dead', '0.0', '0.0', 'dead', '0.0', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
  

In [21]:
l=label[:,]

In [22]:
l=np.where(l=='0.0','survived',l)

In [23]:
l

array(['dead', 'survived', 'survived', 'survived', 'dead', 'dead', 'dead',
       'dead', 'survived', 'survived', 'survived', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived',
       'dead', 'survived', 'survived', 'survived', 'dead', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'survived', 'survived', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'd

In [25]:
from sklearn.model_selection import train_test_split

In [28]:
train_data,train_test,label_train,label_test=train_test_split(features,l,test_size=0.2) 


In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
kclf=KNeighborsClassifier(n_neighbors=5) 

In [31]:
ktrained=kclf.fit(train_data,label_train )

In [32]:
predict_output=ktrained.predict(train_test)

In [33]:
predict_output

array(['survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead',
       'survived', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead',
       'dead', 'survived', 'survived', 'survived', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'survived', 'dead'

In [34]:
label_test

array(['survived', 'survived', 'survived', 'dead', 'dead', 'dead',
       'survived', 'survived', 'dead', 'survived', 'survived', 'dead',
       'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'survived', 'survived', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead',
       'survived', 'survived', 'survived', 'survived', 'dead', 'survived',
       'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead'

In [35]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(label_test,predict_output)

0.7865168539325843